package actors

import akka.actor.{Actor, ActorLogging}

object DeviceActor {
  class SetActivation(value: Double)
  case object On extends SetActivation(1)
  case object Off extends SetActivation(0)
  case class SetActivationValue(value: Double) extends SetActivation(value)

  case object GetLightValue
  case class LightValue(lux: Double)

  case object GetTemperature
  case class Temperature(celsiusTemp: Double)

  case class MoveServo(degrees: Double)

  case class PlayBeep(durationSeconds: Double)

  object GetSoundValue
  case class SoundValue(decibels: Double)

  case object GetSwitchState

  case object Click // generated by button
}

class DeviceActor extends Actor with ActorLogging {

  def receive = {
    case _ => println("pippoooooo")
  }

}









